---
# file: roles/fubarhouse.python/tasks/main.yml

- name: "get home"
  shell: "echo $HOME"
  register: shell_home_dir

- name: "set home"
  set_fact:
    fubarhouse_user_dir: "{{ shell_home_dir.stdout }}"

- name: "Define OS-specific variables"
  include_vars: "config-{{ ansible_os_family }}.yml"
  when: fubarhouse_python is not defined

- include: "dependencies-{{ ansible_os_family}}.yml"

- include: pyenv.yml
  when: fubarhouse_python.install_pyenv

- include: python.yml
  when: fubarhouse_python.install_python

- include: virtualenv.yml

- include: pypi.yml
  when: fubarhouse_python.install_pypi
