---
# file: roles/fubarhouse.python/tasks/main.yml

- name: debug
  debug:
    msg: "{{ fubarhous_user }}"

- name: debug
  debug:
    msg: "{{ fubarhouse_user_dir }}"

- name: "Define OS-specific variables"
  include_vars: "config-{{ ansible_os_family }}.yml"
  when: fubarhouse_python is not defined

- include: "dependencies-{{ ansible_os_family}}.yml"

- include: pyenv.yml
  when: fubarhouse_python.install_pyenv

- include: python.yml
  when: fubarhouse_python.install_python

- include: plugin-updater.yml
- include: plugin-virtualenv.yml

- include: pypi.yml
  when: fubarhouse_python.install_pypi
