---
# file: roles/fubarhouse.python/tasks/pyenv.yml

- name: "PyEnv | Check for pyenv"
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  stat: path={{ pyenv_location }}
  register: pyenv_installed
  ignore_errors: yes
  no_log: yes

- name: "PyEnv | Install"
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  shell: curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
  when: not pyenv_installed.stat.exists

- name: "PyEnv | Initializing"
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  raw: echo 'eval "$({{ pyenv_location }} init -)"' >> ~/.bashrc
  when: not pyenv_installed.stat.exists
