---
# file: roles/fubarhouse.python/tasks/pyenv.yml

- name: "PyEnv | Check for python"
  sudo: yes
  sudo_user: "{{ vagrant_user }}"
  stat: path={{ pyenv_location }}
  register: pyenv_installed
  ignore_errors: yes
  no_log: yes

- name: "PyEnv | Check python versions"
  sudo: yes
  sudo_user: "{{ vagrant_user }}"
  shell: "sudo -iu {{ vagrant_user }} {{ pyenv_location }} versions"
  register: python_installed
  when: pyenv_installed.stat.exists
  ignore_errors: yes
  no_log: yes

- name: "PyEnv | Install"
  sudo: yes
  sudo_user: "{{ vagrant_user }}"
  shell: curl -L https://raw.github.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
  when: not pyenv_installed.stat.exists
