---
# file: roles/fubarhouse.python/tasks/pyenv.yml

- name: "PyEnv | Clean-up"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  file:
    path: "{{ fubarhouse_python.main_dir }}"
    state: absent
  when: fubarhouse_python.clean_install

- name: "PyEnv | Check for pyenv"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  stat:
    path: "{{ fubarhouse_python.main_dir }}"
  register: fubarhouse_python_pyenv_installed
  ignore_errors: yes
  no_log: yes

- name: "PyEnv | Check directory permissions"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  file:
    path: "{{ fubarhouse_python.main_dir }}"
    state: directory
    mode: 0777
    owner: "{{ ansible_ssh_user }}"
    recurse: yes
  when: not fubarhouse_python_pyenv_installed.stat.exists

- name: PyEnv | Cloning/Updating
  become: no
  become_user: "{{ ansible_ssh_user }}"
  git:
    repo: "{{ fubarhouse_python.repo_pyenv }}"
    dest: "{{ fubarhouse_python.main_dir }}"
    clone: yes
    update: yes
    force: yes
    version: master
    recursive: false

- name: PyEnv | Cloning/Updating updater
  become: no
  become_user: "{{ ansible_ssh_user }}"
  git:
    repo: "{{ fubarhouse_python.repo_pyenv_updater }}"
    dest: "{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.updater_path }}"
    clone: yes
    update: yes
    force: yes
    version: master
    recursive: false
  # when: not pyenv_installed.stat.exists

- name: PyEnv | Ensure updated"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.updater_path }}/{{ fubarhouse_python.updater_exec }}"

- name: "PyEnv | Checking initialization"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  raw: cat ~/.bashrc | grep pyenv
  register: fubarhouse_python_pyenv_init
  ignore_errors: yes
  no_log: yes

- name: "PyEnv | Initializing"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  raw: echo 'eval "$({{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.main_path }}/{{ fubarhouse_python.main_exec }} init -)"' >> ~/.bashrc
  when: "'pyenv' not in fubarhouse_python_pyenv_init"
