---
# file: roles/fubarhouse.python/tasks/pypi.yml

- name: "PyPI | Ensure installed and updated"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  pip:
    name: "{{ item.name }}"
    state: latest
    executable: "{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.pypi_path }}/{{ fubarhouse_python.pypi_exec }}"
  with_items: "{{ fubarhouse_python.packages }}"
