---
# file: roles/fubarhouse.python/tasks/pypi.yml

- name: "PyPI | Ensire Installed"
  easy_install:
    name: pip
    state: latest

- name: "PyPI | Ensure installed and updated"
  become: yes
  become_user: "root"
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ python_packages }}"
