---
# file: roles/fubarhouse.python/tasks/pypi.yml

- name: "PyPI | Ensure installed and updated"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ python_packages }}"
