---
# file: roles/fubarhouse.python/tasks/python.yml

- name: "Python | Check python versions"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ pyenv_location }}/{{ pyenv_path_main }}/{{ pyenv_exec_main }} versions"
  register: python_installed
  ignore_errors: yes
  no_log: yes

- name: "Python | Install"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ pyenv_location }}/{{ pyenv_path_main }}/{{ pyenv_exec_main }} install {{ python_version }}"
  when: "'{{ python_version }}' not in '{{ python_installed.stdout }}'"

- name: "Python | Check initialization"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "cat ~/.bashrc | grep '{{ pyenv_location }}'"
  register: python_is_installed
  ignore_errors: yes
  no_log: yes

- name: "Python | Aliasing"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ pyenv_location }}/{{ pyenv_path_main }}/{{ pyenv_exec_main }} global {{ python_version }}"
  when: "'{{ python_version }}' not in '{{ python_installed.stdout }}'"
  # when: "'{{ pyenv_location }} init -' not in {{ python_is_installed }}"
