---
# file: roles/fubarhouse.python/tasks/python.yml

- name: "Python | Check python versions"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.main_path }}/{{ fubarhouse_python.main_exec }} versions"
  register: installed_python_versions

- name: "Python | Install"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.main_path }}/{{ fubarhouse_python.main_exec }} install {{ item }}"
  with_items: "{{ python_versions }}"
  when: '"{{ item }}" not in installed_python_versions.stdout'

- name: "Python | Check initialization"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "cat ~/.bashrc | grep '{{ fubarhouse_python.main_dir }}'"
  register: python_is_installed
  ignore_errors: yes
  no_log: yes

- name: "Python | Aliasing"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.main_path }}/{{ fubarhouse_python.main_exec }} global {{ python_version }}"
  when: "'{{ python_version }}' not in '{{ installed_python_versions.stdout }}'"
