---
# file: roles/fubarhouse.python/tasks/python.yml

- name: "Python | Check python versions"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.main_path }}/{{ fubarhouse_python.main_exec }} versions | grep '{{ fubarhouse_python.python_version }}'"
  register: fubarhouse_python_python_installed
  ignore_errors: yes
  no_log: yes

- name: "Python | Install"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.main_path }}/{{ fubarhouse_python.main_exec }} install {{ fubarhouse_python.python_version }}"
  when: "'{{ fubarhouse_python.python_version }}' not in '{{ fubarhouse_python_python_installed.stdout }}'"

- name: "Python | Check initialization"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "cat ~/.bashrc | grep '{{ fubarhouse_python.main_dir }}'"
  register: python_is_installed
  ignore_errors: yes
  no_log: yes

- name: "Python | Aliasing"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.main_path }}/{{ fubarhouse_python.main_exec }} global {{ fubarhouse_python.python_version }}"
  when: "'{{ fubarhouse_python.python_version }}' not in '{{ fubarhouse_python_python_installed.stdout }}'"
