---
# file: roles/fubarhouse.python/tasks/python.yml

- name: "Python | Run PyEnv / Debug task"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_user_dir }}/{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.main_path }}/{{ fubarhouse_python.main_exec }} commands"

- name: "Python | Run PyEnv / Debug task"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "ls -lah {{ fubarhouse_user_dir }}/"

- name: "Python | Run PyEnv / Debug task"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "cat {{ fubarhouse_user_dir }}/{{ item }}"
  with_items: "{{ fubarhouse_python.shell_profiles }}"
  failed_when: false

- name: "Python | Check python versions"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_user_dir }}/{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.main_path }}/{{ fubarhouse_python.main_exec }} versions"
  register: installed_python_versions

- name: "Python | Install default version"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_user_dir }}/{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.main_path }}/{{ fubarhouse_python.main_exec }} install {{ python_version }}"
  when: '"{{ python_version }}" not in "{{ python_versions }}" and "{{ python_version }}" not in "{{ installed_python_versions.stdout }}"'

- name: "Python | Install all requested versions"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_user_dir }}/{{ fubarhouse_python.main_dir }}/{{ fubarhouse_python.main_path }}/{{ fubarhouse_python.main_exec }} install {{ item }}"
  with_items: "{{ python_versions }}"
  when: '"{{ item }}" not in installed_python_versions.stdout'
